- name: yum module
  hosts: all
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: latest
    - name: installing tree and curl and wget
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages: 
        - tree
        - curl
        - wget

    - name: installing mariadb
      yum:
        name: 
          - mariadb
          - tomcat
        state: latest