- name: privilege escalation
  hosts: all
  tasks: 
    - name: installin git 
      yum: 
        name: git
        state: latest
      become: true
      
# mention inside the configuration file ansible.cfg file
# [privilege_escalation]
#     become = true