- name: yum module
  hosts: all
  become: true
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: latest
    - name: installing tree and curl and wget
      yum:
      vars: packages
        packages: 
          - tree
          - curl
          - wget
        name: {{packages}}
        state: latest