- name: handlers
  hosts: all
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        status: restarted
        enable: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
        notify: restart_httpd