- name: when condition in ansible
  hosts: all
  tasks:
    - name: print os number with condition 
      debug: 
        msg: "this is my {{ ansible_distribution }} machine"
      when: ansible_distribution == "Amazon"
      #when: ansible_distribution == "centos"
      #when: ansible_distribution == "Ubuntu"
    - name: print os number with condition 
      debug: 
        msg: "this is my {{ ansible_distribution }} machine"
      when: ansible_distribution == "Amazon" and ansible_os_family = "RedHat"